apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability-dashboard.fullname" . }}
  namespace: {{ include "observability-dashboard.namespace" . }}
  labels:
    {{- include "observability-dashboard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "observability-dashboard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "observability-dashboard.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: observability-dashboard
          image: {{ include "observability-dashboard.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            httpGet:
              port: {{ .Values.readinessProbe.httpGet.port }}
              path: {{ .Values.readinessProbe.httpGet.path }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              port: {{ .Values.livenessProbe.httpGet.port }}
              path: {{ .Values.livenessProbe.httpGet.path }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
