{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "observability-dashboard.namespace" . }}
  labels:
    {{- include "observability-dashboard.labels" . | nindent 4 }}
{{- end }}
