apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-dashboard.fullname" . }}
  namespace: {{ include "observability-dashboard.namespace" . }}
  labels:
    {{- include "observability-dashboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "observability-dashboard.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
